name = "SMLMRender"
uuid = "d945b928-cd23-4282-89d9-fc086b52682d"
version = "1.0.0-DEV"
authors = ["klidke@unm.edu"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ColorSchemes = "3.26"
Colors = "0.12"
FileIO = "1.17.1"
ImageIO = "0.6.9"
PNGFiles = "0.4.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
