[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MicroscopePSFs = "de9ac726-48a4-48ab-84b0-1c03c7c18929"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
