[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
MicroscopePSFs = "de9ac726-48a4-48ab-84b0-1c03c7c18929"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMRender = "d945b928-cd23-4282-89d9-fc086b52682d"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
