[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMRender = "d945b928-cd23-4282-89d9-fc086b52682d"

[compat]
Documenter = "1"
